import React, { useState, useEffect } from 'react';
import { totpApi } from '../api/totp';
import { useToastStore } from '../store/toastStore';
import { QRCodeSVG } from 'qrcode.react';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Dialog } from '../components/ui/Dialog';
import { ShieldCheck, Copy, Check, ShieldAlert } from 'lucide-react';

export const Setup2FA: React.FC = () => {
  const { push: pushToast } = useToastStore();

  const [is2faEnabled, setIs2faEnabled] = useState<boolean>(false);
  const [secret, setSecret] = useState<string>('');
  const [otpauthUrl, setOtpauthUrl] = useState<string>('');
  const [verifyCode, setVerifyCode] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  // Disable dialog state
  const [isDisableOpen, setIsDisableOpen] = useState<boolean>(false);
  const [passwordConfirm, setPasswordConfirm] = useState<string>('');
  const [disableLoading, setDisableLoading] = useState<boolean>(false);

  useEffect(() => {
    // In our user payload, check if 2fa is active
    setIs2faEnabled(false); // Default or check state
    loadSetup();
  }, []);

  const loadSetup = async () => {
    try {
      const res = await totpApi.setup();
      if (res.success && res.data) {
        setSecret(res.data.secret);
        setOtpauthUrl(res.data.otpauth_url);
      }
    } catch {
      // User might already have 2FA enabled
      setIs2faEnabled(true);
    }
  };

  const handleCopySecret = () => {
    if (secret) {
      navigator.clipboard.writeText(secret);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleEnable2FA = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!verifyCode.trim()) return;
    setIsLoading(true);

    try {
      const res = await totpApi.enable(secret, verifyCode.trim());
      if (res.success) {
        pushToast('success', 'Two-Factor Authentication is now enabled on your account!');
        setIs2faEnabled(true);
        setVerifyCode('');
      } else {
        pushToast('error', res.message || 'Invalid 2FA code. Please try again.');
      }
    } catch (err: any) {
      pushToast('error', err.message || 'Verification failed');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDisable2FA = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!passwordConfirm) return;
    setDisableLoading(true);

    try {
      const res = await totpApi.disable(passwordConfirm);
      if (res.success) {
        pushToast('success', 'Two-Factor Authentication has been disabled.');
        setIs2faEnabled(false);
        setIsDisableOpen(false);
        setPasswordConfirm('');
        loadSetup();
      } else {
        pushToast('error', res.message || 'Incorrect password.');
      }
    } catch (err: any) {
      pushToast('error', err.message || 'Failed to disable 2FA');
    } finally {
      setDisableLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="text-xl font-bold tracking-tight text-gray-900 dark:text-gray-100">
          Two-Factor Authentication (2FA)
        </h1>
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
          Enhance your account security using Google Authenticator, Authy, or 1Password
        </p>
      </div>

      <div className="p-6 rounded-xl border border-border dark:border-border-dark bg-surface dark:bg-surface-dark shadow-xs space-y-6">
        <div className="flex items-center justify-between pb-4 border-b border-border dark:border-border-dark">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-brand/10 text-brand">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <span className="text-sm font-semibold text-gray-900 dark:text-gray-100 block">
                Status
              </span>
              <span className="text-xs text-gray-500">
                {is2faEnabled ? 'Your account is guarded by 2FA.' : '2FA is currently not configured.'}
              </span>
            </div>
          </div>

          <Badge variant={is2faEnabled ? 'green' : 'gray'}>
            {is2faEnabled ? 'Active' : 'Not Configured'}
          </Badge>
        </div>

        {is2faEnabled ? (
          <div className="space-y-4">
            <p className="text-xs text-gray-600 dark:text-gray-300">
              When logging in from a new browser session, you will be required to provide a 6-digit TOTP code generated by your mobile authenticator application.
            </p>

            <Button
              variant="danger"
              size="sm"
              onClick={() => setIsDisableOpen(true)}
            >
              <ShieldAlert className="w-4 h-4" />
              Disable Two-Factor Authentication
            </Button>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="space-y-2">
              <h2 className="text-xs font-semibold text-gray-900 dark:text-gray-100 uppercase tracking-wider">
                Step 1: Scan QR Code
              </h2>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Open your authenticator app (Google Authenticator, Microsoft Authenticator, Authy) and scan this barcode:
              </p>

              {otpauthUrl && (
                <div className="p-4 bg-white rounded-xl inline-block border border-gray-200 shadow-xs my-2">
                  <QRCodeSVG value={otpauthUrl} size={180} />
                </div>
              )}
            </div>

            <div className="space-y-2">
              <h2 className="text-xs font-semibold text-gray-900 dark:text-gray-100 uppercase tracking-wider">
                Manual Setup Secret
              </h2>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Cannot scan the barcode? Enter this secret manually into your authenticator app:
              </p>

              <div className="flex items-center gap-2 max-w-sm">
                <input
                  type="text"
                  readOnly
                  value={secret}
                  className="px-3 py-2 text-xs font-mono rounded-lg border border-border dark:border-border-dark bg-elevated dark:bg-elevated-dark text-gray-900 dark:text-gray-100 select-all flex-1"
                />
                <Button size="sm" variant="outline" onClick={handleCopySecret}>
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                </Button>
              </div>
            </div>

            <div className="space-y-3 pt-4 border-t border-border dark:border-border-dark">
              <h2 className="text-xs font-semibold text-gray-900 dark:text-gray-100 uppercase tracking-wider">
                Step 2: Verify Activation Code
              </h2>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Type the 6-digit confirmation code shown on your phone to activate 2FA:
              </p>

              <form onSubmit={handleEnable2FA} className="flex items-center gap-3 max-w-xs">
                <input
                  type="text"
                  required
                  maxLength={6}
                  placeholder="123456"
                  value={verifyCode}
                  onChange={(e) => setVerifyCode(e.target.value)}
                  className="px-3 py-2 text-sm font-mono tracking-widest rounded-lg border border-border dark:border-border-dark bg-elevated dark:bg-elevated-dark text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-brand/40 flex-1"
                />
                <Button type="submit" variant="primary" size="md" isLoading={isLoading}>
                  Activate 2FA
                </Button>
              </form>
            </div>
          </div>
        )}
      </div>

      {/* Disable 2FA Password Dialog */}
      <Dialog
        isOpen={isDisableOpen}
        onClose={() => setIsDisableOpen(false)}
        title="Confirm 2FA Removal"
      >
        <form onSubmit={handleDisable2FA} className="space-y-4">
          <p className="text-xs text-gray-600 dark:text-gray-300">
            To disable Two-Factor Authentication, please re-enter your current account password to verify your identity.
          </p>

          <div>
            <label className="block text-xs font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
              Account Password
            </label>
            <input
              type="password"
              required
              value={passwordConfirm}
              onChange={(e) => setPasswordConfirm(e.target.value)}
              placeholder="••••••••••••"
              className="w-full px-3 py-2 text-sm rounded-lg border border-border dark:border-border-dark bg-elevated dark:bg-elevated-dark text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-brand/40"
            />
          </div>

          <div className="flex items-center justify-end gap-2 pt-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => setIsDisableOpen(false)}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="danger"
              size="sm"
              isLoading={disableLoading}
            >
              Disable 2FA
            </Button>
          </div>
        </form>
      </Dialog>
    </div>
  );
};
